
create schema bibliotecabd;
use bibliotecabd;

CREATE TABLE LIBRO (
  LIBRO_ID int PRIMARY KEY AUTO_INCREMENT ,
  TITULO varchar(50),
  AUTOR varchar(50),
  EDITORIAL varchar(20),
  IDIOMA varchar(20),
  DESCRIPCION varchar(100),
  MULTA decimal(5,2) CHECK (MULTA >= 0),
  STOCK_ACTUAL INT,
  CANTIDAD_PRESTADO INT
  
) ;

CREATE TABLE CLIENTE(
CLIENTE_ID int PRIMARY KEY AUTO_INCREMENT,
DNI char(8) UNIQUE,
NOMBRE VARCHAR(15),
APELLIDO_PA VARCHAR(20),
APELLIDO_MA VARCHAR(20),
DIRECCION VARCHAR(50),
TELEFONO INT,
EMAIL VARCHAR(50)
) ;

CREATE TABLE PRESTAMO(
PRESTAMO_ID int PRIMARY KEY AUTO_INCREMENT,
FECHA_PRESTAMO DATE,
FECHA_DEVOLUCION DATE,
CLIENTE_ID INT,
CANTIDAD INT,
ESTADO VARCHAR(20) DEFAULT 'Prestado',
MULTA_TOTAL DECIMAL(10,5),
FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(CLIENTE_ID)
) ;

CREATE TABLE DETALLE_PRESTAMO (
    DETALLE_ID INT AUTO_INCREMENT PRIMARY KEY,
    LIBRO_ID INT,
    PRESTAMO_Id INT,
    FOREIGN KEY (LIBRO_ID) REFERENCES LIBRO(LIBRO_ID),
    FOREIGN KEY (PRESTAMO_Id) REFERENCES PRESTAMO(PRESTAMO_Id)
);

insert into Libro(TITULO, AUTOR, EDITORIAL, IDIOMA, DESCRIPCION, multa, stock_Actual, cantidad_prestado)
	values("libro1", "autor1", "editorial", "ingles", "pequeña descripcion de la pelicula", 3, 5, 1);
    
insert into cliente(DNI, NOMBRE, APELLIDO_PA, APELLIDO_MA, DIRECCION, TELEFONO, EMAIL)
	values ("12345678","rodrigo","leon","franco","av28dejuli1340", 943674007,"rleonf1803@gmail");
    
    